log:
  level: debug
  disable_sentry: true

db:
  url: postgres://postgres:bestuser@localhost:5432/reviewApi?sslmode=disable

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://localhost:90"
  upstream: "http://localhost:88"
  service_name: review-api
  service_port: 80
