patch:
  summary: Update rating by rating id
  operationId: updateRating
  tags:
    - Rating
  parameters:
    - $ref: '#/components/parameters/product_id'
    - $ref: '#/components/parameters/review_id'
    - $ref: '#/components/parameters/rating_id'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/UpdateRatingRequest'
  responses:
    '200':
      description: Rating updated successfully
    '400':
      description: Invalid request parameters
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/JsonApiErrors'
          examples:
            BadRequestExample:
              $ref: '#/components/examples/BadRequestError'
    '500':
      description: Internal server error
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/JsonApiErrors'
          examples:
            InternalServerErrorExample:
              $ref: '#/components/examples/InternalServerError'
delete:
  tags:
    - Rating
  summary: Delete rating by id
  operationId: deleteByRatingId
  parameters:
    - $ref: '#/components/parameters/product_id'
    - $ref: '#/components/parameters/review_id'
    - $ref: '#/components/parameters/rating_id'
  responses:
    '201':
      description: Rating deleted successfully
    '400':
      description: Invalid request parameters
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/JsonApiErrors'
          examples:
            BadRequestExample:
              $ref: '#/components/examples/BadRequestError'
    '500':
      description: Internal server error
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/JsonApiErrors'
          examples:
            InternalServerErrorExample:
              $ref: '#/components/examples/InternalServerError'
