post:
  summary: Create new rating for a review
  operationId: createRating
  tags:
    - Rating
  parameters:
    - $ref: '#/components/parameters/product_id'
    - $ref: '#/components/parameters/review_id'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/CreateRatingRequest'
  responses:
    '200':
      description: Rating created successfully
    '400':
      description: Invalid request parameters
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/JsonApiErrors'
          examples:
            BadRequestExample:
              $ref: '#/components/examples/BadRequestError'
    '500':
      description: Internal server error
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/JsonApiErrors'
          examples:
            InternalServerErrorExample:
              $ref: '#/components/examples/InternalServerError'
patch:
  summary: Update review by review id
  operationId: updateReview
  tags:
    - Review
  parameters:
    - $ref: '#/components/parameters/product_id'
    - $ref: '#/components/parameters/review_id'
  requestBody:
    required: true
    content:
      application/vnd.api+json:
        schema:
          $ref: '#/components/schemas/UpdateReviewRequest'
  responses:
    '201':
      description: Review updated successfully
    '400':
      description: Invalid request parameters
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/JsonApiErrors'
          examples:
            BadRequestExample:
              $ref: '#/components/examples/BadRequestError'
    '500':
      description: Internal server error
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/JsonApiErrors'
          examples:
            InternalServerErrorExample:
              $ref: '#/components/examples/InternalServerError'
