post:
  tags:
    - Review
  summary: Create a new review for a product
  operationId: createReview
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/CreateReviewRequest'
  responses:
    '201':
      description: Review created successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateReviewRequest'
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/APIError'
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/APIError'
get:
  tags:
    - Review
  summary: Get reviews for a product
  operationId: getReviews
  responses:
    '200':
      description: List of reviews
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GetReviewRequest'
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/APIError'
delete:
  tags:
    - Review
  summary: Delete all reviews for a product
  operationId: deleteAllByProductId
  responses:
    '200':
      description: Reviews deleted successfully
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/APIError'
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/APIError'
