post:
  summary: Create a new review for a product
  operationId: createReview
  tags:
    - Review
  parameters:
    - $ref: '#/components/parameters/product_id'
  requestBody:
    required: true
    content:
      application/vnd.api+json:
        schema:
          type: object
          required: [data]
          properties:
            data:
              type: object
              required:
                - type
                - attributes
              properties:
                type:
                  type: string
                  description: "Type of the resource"
                  example: "reviews"
                attributes:
                  $ref: '#/components/schemas/CreateReviewRequest'
  responses:
    '201':
      description: Review created successfully
    '400':
      description: Bad request
    '500':
      description: Internal server error
get:
  summary: Get reviews for a product
  operationId: getReviews
  tags:
    - Review
  parameters:
    - $ref: '#/components/parameters/product_id'
    - $ref: '#/components/parameters/page_limit_param'
    - $ref: '#/components/parameters/page_number_param'
    - $ref: '#/components/parameters/sorting_param'
  responses:
    '200':
      description: List of reviews
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/components/schemas/ReviewWithRatings'
    '400':
      description: Invalid request parameters
    '500':
      description: Internal server error
delete:
  tags:
    - Review
  summary: Delete all reviews for a product
  operationId: deleteByProductId
  parameters:
    - $ref: '#/components/parameters/product_id'
  responses:
    '201':
      description: Reviews deleted successfully
    '400':
      description: Bad request
    '500':
      description: Internal server error